version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/apps/web'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    groups:
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
      react-email:
        patterns:
          - '@react-email/*'
          - 'react-email'
      next:
        patterns:
          - 'next'
          - 'eslint-config-next'
      prisma:
        patterns:
          - '@prisma/client'
          - 'prisma'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'